import type { Metadata } from "next";
import { rotis } from "./fonts"

import "../styles/globals.scss"

export const metadata: Metadata = {
  title: "Blackwell Global | Interview Test - Tan Yin Yin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rotis.className}`}>
        {children}
      </body>
    </html>
  );
}
