import type { Metadata } from "next";
import { rotis } from "./fonts"
import { I18nProvider } from '@/context/I18nContext'

import "../styles/globals.scss"

export const metadata: Metadata = {
  title: "Blackwell Global | Interview Test - Tan Yin Yin",
  description: "Generated by create next app",
  icons: {
    icon: "./blackwell/favicon.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rotis.className}`}>
        <I18nProvider>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
